# Base image
FROM hashicorp/vault:1.13.2

# Set working directory
WORKDIR /etc/vault

# Copy custom Vault configuration
COPY config.hcl /etc/vault/config.hcl

# Expose Vault HTTP port (8200 is default)
EXPOSE 8200

# Run Vault agent in a loop
CMD ["vault", "agent", "-config=/etc/vault/config.hcl"]
